### PR TITLE
Be more lenient towards invalid VAST sources

### PR DESCRIPTION
**Pull request by pietermees**
Not all VAST files in the wild seem to comply with the standards. In this case, I was encountering a duplicate Creative node without contents.

Proposal: ignore invalid nodes rather than killing the whole parse process with an error?

### CODE REVIEW

**Comment by delbeke** [comment]
Tim and briefly discussed this before, because I will encounter similar issues with out-stream. The suggestion at that time was to introduce a `strict` flag to change the behavior of the parser. The default could be `false`, since that is probably the most common scenario.

In this case the strict flag could rethrow the error (JavaScript preserves the original call-stack when you rethrow).

**Comment by timdp** [comment]
I'm not a fan of empty catch blocks, but I definitely agree that we need a solution.

My proposal, which I may have already mentioned under another issue, would be to introduce a `strict` option that's `false` by default (or `loose` if we want to default to strict mode).

Strict mode would essentially throw immediately whenever it's not sure what to do. I believe that would also be the case for your earlier PR that deals with invalid Ad subtypes.

Ideally, we'd then throw whenever a document isn't 100℅ VAST-compliant, but that would really increase our footprint. Users are still free to validate their XML against an XSD, of course.

**Comment by timdp** [comment]
Great, concurrent replies. Well, at least we agree.

**Comment by delbeke** [comment]
What are the odds at 9 am on a Saturday 😉

**Comment by pietermees** [comment]
Apparently greater than we thought ;)

**Comment by pietermees** [comment]
For what it's worth: I do agree

**Comment by pietermees** [comment]
Updated. What do you think @timdp @delbeke

**Comment by timdp** [comment]
I like it (apart from the coverage that dropped).

One note: in iab-vast-loader, we're [working on typed errors](https://github.com/zentrick/iab-vast-loader/tree/typed-errors). Perhaps now's a good opportunity to do that here too?

**Comment by pietermees** [comment]
Hmm, I guess I'll have to extend the test framework a bit more to test broken scenarios and cover the error handling lines

**Comment by pietermees** [comment]
@timdp ok, got the coverage fixed. For typed errors, could we set that aside as a todo? I assume the current PR is already an improvement on the current state?

**Comment by pietermees** [comment]
@timdp FYI this PR is needed for a PulsePoint issue

**Comment by timdp** [comment]
Agreed, let's merge. I'll create an issue for the typed errors.

**Pull request merged**
